name: CI

on: [push, pull_request]

jobs:
  content_checks:
    name: Content checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ./make.sh
      - name: Link check
        run: ./make.sh linkcheck
